add ret code check

diff --git a/wmail/install b/wmail/install
--- a/wmail/install
+++ b/wmail/install
@@ -6,6 +6,8 @@ else
         PREFIX=$1
 fi
 
+RETVAL=0
+
 ./configure --prefix=$PREFIX/wmail \
         --enable-cgibindir=$PREFIX/wmail/www/cgi-bin \
         --enable-imagedir=$PREFIX/wmail/www/image \
@@ -22,8 +24,28 @@ fi
         --enable-https=auto \
         --with-cacheowner=vpopmail
 
+RETVAL=$?
+[ $RETVAL != 0 ] && echo "Configure Error!" && exit 1
+
 make configure-check
 make 
+
+RETVAL=$?
+[ $RETVAL != 0 ] && echo "Compile Error!" && exit 1
+
 make check
+
+RETVAL=$?
+[ $RETVAL != 0 ] && echo "Function Check Error!" && exit 1
+
 make install-strip
 make install-configure
+
+RETVAL=$?
+[ $RETVAL != 0 ] && echo "File Copying Error!" && exit 1
+
+printf "\n\n\x1b[1;33m"
+echo "   WMail installed completed!     "
+echo "Welcome to visit http://www.aka.cn"
+echo "     Fan Lin <lfan@lfan.net>      "
+printf "\x1b[m"
